### ISSUE TITLE
No trade buttons?

### ISSUE THREAD

**Issue by fbjerggaard** [jannolii/discourse-topic-trade-buttons#3]
I don't see the trade buttons on my site using the newest Discourse install. I see some of the code for generating the buttons but there are no buttons visible

**Comment by jannolii** [comment]
You have to enable desired buttons in category settings. Also you may have to restart discourse instance for plugin to take effect.

**Comment by fbjerggaard** [comment]
Restarting the discourse instance fixed it - thanks!

**Comment by pieman64** [comment]
Installed the plugin and I will try the Discourse restart later to see if the buttons start to appear.

Yes a rebuild made the buttons appear.
